export const blogTypes = {
  all: 'All posts',
  tips: 'Tips',
  design: 'Design',
  marketing: 'Marketing',
};

export const blogs = [
  {
    id: 1,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 2,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 3,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 11, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 4,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 5,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 6,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 7,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 8,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 9,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 10,
    type: [blogTypes.all, blogTypes.tips],
    image: './image/blog/001.jpg',
    createdTime: 'April 15, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Storytelling is so Important for a Brand',
  },
  {
    id: 11,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 12,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 13,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 14,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 15,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 16,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 17,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 18,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 19,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 20,
    type: [blogTypes.all, blogTypes.design],
    image: './image/blog/002.jpg',
    createdTime: 'April 8, 2022',
    creater: 'Ramzi Chamat',
    heading: 'How To Create A Stunning Website For Your Hospitality Business',
  },
  {
    id: 21,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 22,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 23,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 24,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 25,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 26,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 27,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 28,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 29,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
  {
    id: 30,
    type: [blogTypes.all, blogTypes.marketing],
    image: './image/blog/003.jpg',
    createdTime: 'April 13, 2022',
    creater: 'Ramzi Chamat',
    heading: 'Why Conversion is Important for Luxury Hotels and How to Improve Yours',
  },
];
